#!/bin/bash

SOURCE_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
BUILD_DIRECTORY=`pwd`

Trilinos_DIR="/imcs/public/compsim/lib/2022_2/build/lib/cmake/Trilinos"

echo "Source and build directory:"
echo "-- Path to source code:    " $SOURCE_DIRECTORY
echo "-- Path to build directory:" $BUILD_DIRECTORY

cmake \
  -D TRILINOS_IN_MIRCO:BOOL="ON" \
  -D GTEST_IN_MIRCO:BOOL="OFF" \
  -D TRILINOS_PATH:PATH="${Trilinos_DIR}" \
  -D CMAKE_INSTALL_PREFIX:PATH="${BUILD_DIRECTORY}" \
  "${SOURCE_DIRECTORY}"

