
#define HAVE_MUELU_EXPLICIT_INSTANTIATION
#define HAVE_MUELU_EXPERIMENTAL

#define HAVE_MUELU_INST_DOUBLE_INT_INT
/* #undef HAVE_MUELU_INST_DOUBLE_INT_LONGLONGINT */
/* #undef HAVE_MUELU_INST_COMPLEX_INT_INT */
/* #undef HAVE_MUELU_INST_PCE_INT_INT */
