name: mirco_ci

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  schedule:
    - cron: '00 6 * * *'
  workflow_dispatch:

jobs:
  code-check:
    name: code_check
    runs-on: ubuntu-latest
    env:
      CTEST_FAIL_ON_WARNING: "1"
    steps:
      - uses: actions/checkout@v5
      - name: Check code.
        run: |
          source create-mirco-python-venv.sh
          find src/ tests/ -iname *.h -o -iname *.c -o -iname *.cpp -o -iname *.hpp | xargs clang-format -style=file -i -fallback-style=none
          git diff > clang_format.patch
          if [ -s clang_format.patch ]
          then
            echo "Formatting incorrect. Run 'source create-mirco-python-venv.sh && find src/ tests/ -iname *.h -o -iname *.c -o -iname *.cpp -o -iname *.hpp | xargs clang-format -style=file -i -fallback-style=none && deactivate' in your local source directory and push it."
            exit 1
          fi

  mirco-test-kokkosserial:
    name: mirco_test_kokkosserial
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/imcs-compsim/mirco-dependencies:latest

    env:
      CTEST_FAIL_ON_WARNING: "1"

    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v5
        with:
          submodules: recursive
          path: mirco-src
          fetch-depth: 0  # Necessary for full git history and tags

      - name: Build and test
        run: |
          mkdir mirco-build_kokkosserial
          cd mirco-build_kokkosserial
          cmake --preset=docker_container_kokkosserial ../mirco-src/
          ninja -j 12
          ctest --output-on-failure
          cd ..&&rm -rf mirco-build_kokkosserial

  mirco-test-kokkosopenmp:
    name: mirco_test_kokkosopenmp
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/imcs-compsim/mirco-dependencies:latest

    env:
      CTEST_FAIL_ON_WARNING: "1"

    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v5
        with:
          submodules: recursive
          path: mirco-src
          fetch-depth: 0  # Necessary for full git history and tags

      - name: Build and test
        run: |
          mkdir mirco-build_kokkosopenmp
          cd mirco-build_kokkosopenmp
          cmake --preset=docker_container_kokkosopenmp ../mirco-src/
          ninja -j 12
          ctest --output-on-failure
          cd ..&&rm -rf mirco-build_kokkosopenmp

  mirco-buildtest-kokkoscuda:
    name: mirco_buildtest_kokkoscuda
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/imcs-compsim/mirco-dependencies:latest

    env:
      CTEST_FAIL_ON_WARNING: "1"

    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v5
        with:
          submodules: recursive
          path: mirco-src
          fetch-depth: 0  # Necessary for full git history and tags

      - name: Build and test
        run: |
          mkdir mirco-build_kokkoscuda
          cd mirco-build_kokkoscuda
          cmake --preset=docker_container_kokkoscuda ../mirco-src/
          ninja -j 1
          #ctest --output-on-failure
          rm -rf *
          cmake --preset=docker_container_kokkoscuda_clangcuda++ ../mirco-src/
          ninja -j 1
          #ctest --output-on-failure
          cd ..&&rm -rf mirco-build_kokkosopenmp
